version: '2'
services:
    accommodation-booking-system:
      image: raestio/accommodation-booking-system:latest
      ports: 
          - 8080:8080
      depends_on:
          - db
      command: ["./wait-for-postgres.sh", "db", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    db:
        container_name: accommodation-booking-system-db
        image: postgres:9.5
        volumes:
            - ../database-scripts/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
            - ../database-scripts/insert.sql:/docker-entrypoint-initdb.d/2-insert.sql.sql
            - accommodation-booking-system-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=postgres
            - POSTGRES_DB=accommodation_booking_system_database
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    accommodation-booking-system-db: {}
